import{a as f,S as y,i as h}from"./assets/vendor-06b1bbdf.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))u(t);new MutationObserver(t=>{for(const s of t)if(s.type==="childList")for(const n of s.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&u(n)}).observe(document,{childList:!0,subtree:!0});function r(t){const s={};return t.integrity&&(s.integrity=t.integrity),t.referrerPolicy&&(s.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?s.credentials="include":t.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function u(t){if(t.ep)return;t.ep=!0;const s=r(t);fetch(t.href,s)}})();const g="https://pixabay.com/api/",v="45194494-dd5a842bfc997d055f9644a50";async function L(e,o=1){try{return(await f.get(g,{params:{key:v,q:e,image_type:"photo",orientation:"horizontal",safesearch:!0,page:o,per_page:15}})).data}catch(r){throw izitoast.error("Error fetching images:",r),r}}const w=document.querySelector(".gallery-list"),x=new y(".gallery-list a",{captions:!0,captionsData:"alt",captionsDelay:250});function S(e){let o=e.hits.map(r=>`<div class="image-wrapper">
    <a href="${r.largeImageURL}">
    <img class="gallery-img" src="${r.webformatURL}" alt="${r.tags}"></img>
    </a>
    <div class="text-wrapper">
    <div class="text-item"><h5 class="text-header">Likes</h5><p class="text-paragraph">${r.likes}</p></div>
    <div class="text-item"><h5 class="text-header">Views</h5><p class="text-paragraph">${r.views}</p></div>
    <div class="text-item"><h5 class="text-header">Comments</h5><p class="text-paragraph">${r.comments}</p></div>
    <div class="text-item"><h5 class="text-header">Downloads</h5><p class="text-paragraph">${r.downloads}</p></div>
    </div>
    </div>`).join("");w.insertAdjacentHTML("beforeend",o),x.refresh()}function b(){const e=document.querySelector(".gallery-list");e.innerHTML=""}const p=document.querySelector(".form-gallery"),q=document.querySelector(".form-gallery-input"),c=document.querySelector(".loader"),l=document.querySelector(".load-more"),a=document.querySelector(".scroll-to-top");let i=1,d="";p.addEventListener("submit",T);l.addEventListener("click",E);a.addEventListener("click",B);async function T(e){e.preventDefault(),b(),c.classList.remove("hidden"),d=q.value.trim(),i=1,await m(),p.reset()}async function E(){i+=1,await m()}async function m(){try{const e=await L(d,i);if(c.classList.add("hidden"),e.total===0||d===""){h.error({position:"topRight",message:"Sorry, there are no images matching your search query. Please try again!"});return}S(e),e.hits.length===0||i*15>=e.totalHits?(l.classList.add("hidden"),h.info({position:"topRight",message:"We're sorry, but you've reached the end of search results."})):l.classList.remove("hidden"),P(),$()}catch(e){console.error(e),c.classList.add("hidden")}}function P(){const{height:e}=document.querySelector(".gallery-list").firstElementChild.getBoundingClientRect();window.scrollBy({top:e*2,behavior:"smooth"})}function $(){window.scrollY>1e3?a.classList.remove("hidden"):a.classList.add("hidden")}function B(){window.scrollTo({top:0,behavior:"auto"})}window.addEventListener("scroll",a);
//# sourceMappingURL=commonHelpers.js.map
